### ISSUE TITLE
Run On Browsers does not work (Win7)

### ISSUE THREAD

**Issue by p0wl** [azer/prova-retired#1]
I've installed fox using `npm install -g fox` and created a test.js with your example code.

`fox test` does work in the console, but `fox test -b` gives the error:

![fox](https://f.cloud.github.com/assets/596578/290658/715c74b0-92eb-11e2-9577-09ed9698017f.JPG)

After opening `http://localhost:7559/` in chrome (gives an empty page, title is "fox", another error appears in the console:

![fox2](https://f.cloud.github.com/assets/596578/290662/937e05cc-92eb-11e2-8588-f87a81b74384.JPG)

Specs: 
- Win7 (64Bit)
- node -v: v0.10.1 (updated after 0.8.8 didn't work either)
- fox -v: v0.0.5

Thanks for your library, looking forward to use it in detail!

**Comment by azer** [comment]
It fails to compile your project for web browsers. I'm sorry but you better use a unix system for development. Windows is not open source, so I can't support it.
